USE [master]
GO

/****** Object:  Database [FileSystem]    Script Date: 29.2.2024. 19:09:14 ******/
CREATE DATABASE [FileSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FileSystem', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FileSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FileSystem_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FileSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FileSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FileSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FileSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FileSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FileSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FileSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [FileSystem] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [FileSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FileSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FileSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FileSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FileSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FileSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FileSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FileSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FileSystem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FileSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FileSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FileSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FileSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FileSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FileSystem] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [FileSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FileSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FileSystem] SET  MULTI_USER 
GO

ALTER DATABASE [FileSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FileSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FileSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FileSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FileSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FileSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FileSystem] SET QUERY_STORE = ON
GO

ALTER DATABASE [FileSystem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [FileSystem] SET  READ_WRITE 
GO


USE [FileSystem]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Folder](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FolderName] [nvarchar](128) NOT NULL,
	[ParentFolderId] [bigint] NULL,
	[Size] [bigint] NOT NULL,
	[FullPath] [nvarchar](max) NOT NULL,
	[Active] [bit] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[DeletedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_Folder] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Folder]  WITH CHECK ADD  CONSTRAINT [FK_Folder_Folder_ParentFolderId] FOREIGN KEY([ParentFolderId])
REFERENCES [dbo].[Folder] ([Id])
GO

ALTER TABLE [dbo].[Folder] CHECK CONSTRAINT [FK_Folder_Folder_ParentFolderId]
GO



CREATE TABLE [dbo].[File](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FileName] [nvarchar](128) NOT NULL,
	[StoredFileName] [nvarchar](max) NOT NULL,
	[Size] [bigint] NOT NULL,
	[FolderId] [bigint] NOT NULL,
	[Active] [bit] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[DeletedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_File] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[File]  WITH CHECK ADD  CONSTRAINT [FK_File_Folder_FolderId] FOREIGN KEY([FolderId])
REFERENCES [dbo].[Folder] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[File] CHECK CONSTRAINT [FK_File_Folder_FolderId]
GO



INSERT INTO [dbo].[Folder]
           ([FolderName]
           ,[ParentFolderId]
           ,[Size]
           ,[FullPath]
           ,[Active]
           ,[CreatedDate]
           ,[LastModifiedDate]
           ,[DeletedDate])
     VALUES
           (''
           ,null
           ,0
           ,'\'
           ,1
           ,'0001-01-01 00:00:00.0000000'
           ,null
           ,null)

GO
